# Generated by Django 4.1.1 on 2022-09-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=70, verbose_name='Apellidos')),
                ('direccion', models.CharField(max_length=70)),
                ('poblacion', models.CharField(max_length=70)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('provincia', models.CharField(default='Valencia', max_length=50)),
                ('telefono_fijo', models.CharField(blank=True, max_length=15)),
                ('telefono_movil', models.CharField(max_length=15)),
                ('telefono_otro', models.CharField(blank=True, max_length=15)),
                ('correo_electronico', models.EmailField(blank=True, default='', max_length=100)),
                ('observaciones', models.TextField(blank=True, max_length=250)),
                ('numero_socio', models.IntegerField(default=0)),
            ],
        ),
    ]
