# Generated by Django 4.1.1 on 2022-09-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=70)),
                ('direccion', models.CharField(max_length=70)),
                ('poblacion', models.CharField(max_length=70)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('telefono_fijo', models.CharField(max_length=15)),
                ('telefono_movil', models.CharField(max_length=15)),
                ('telefono_otro', models.CharField(max_length=15)),
            ],
        ),
    ]
