# Generated by Django 4.1.1 on 2022-09-23 23:48

from django.db import migrations, models
import localflavor.es.models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='dni',
            field=localflavor.es.models.ESIdentityCardNumberField(default='46', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socio',
            name='codigo_postal',
            field=localflavor.es.models.ESPostalCodeField(max_length=5),
        ),
        migrations.AlterField(
            model_name='socio',
            name='provincia',
            field=models.CharField(choices=[('01', 'Araba'), ('02', 'Albacete'), ('03', 'Alacant'), ('04', 'Almeria'), ('05', 'Avila'), ('06', 'Badajoz'), ('07', 'Illes Balears'), ('08', 'Barcelona'), ('09', 'Burgos'), ('10', 'Caceres'), ('11', 'Cadiz'), ('12', 'Castello'), ('13', 'Ciudad Real'), ('14', 'Cordoba'), ('15', 'A Coruna'), ('16', 'Cuenca'), ('17', 'Girona'), ('18', 'Granada'), ('19', 'Guadalajara'), ('20', 'Guipuzkoa'), ('21', 'Huelva'), ('22', 'Huesca'), ('23', 'Jaen'), ('24', 'Leon'), ('25', 'Lleida'), ('26', 'La Rioja'), ('27', 'Lugo'), ('28', 'Madrid'), ('29', 'Malaga'), ('30', 'Murcia'), ('31', 'Navarre'), ('32', 'Ourense'), ('33', 'Asturias'), ('34', 'Palencia'), ('35', 'Las Palmas'), ('36', 'Pontevedra'), ('37', 'Salamanca'), ('38', 'Santa Cruz de Tenerife'), ('39', 'Cantabria'), ('40', 'Segovia'), ('41', 'Seville'), ('42', 'Soria'), ('43', 'Tarragona'), ('44', 'Teruel'), ('45', 'Toledo'), ('46', 'Valencia'), ('47', 'Valladolid'), ('48', 'Bizkaia'), ('49', 'Zamora'), ('50', 'Zaragoza'), ('51', 'Ceuta'), ('52', 'Melilla')], default='46', max_length=2),
        ),
    ]
