# Generated by Django 4.1.1 on 2022-09-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_socio_dni_alter_socio_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='fecha de nacimiento'),
        ),
    ]
