# Generated by Django 4.1.1 on 2022-09-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_socio_correo_electronico_socio_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='socio',
            name='telefono_otro',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
