# Generated by Django 4.1.1 on 2022-09-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_socio_fecha_alta_socio_fecha_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='fecha de nacimiento'),
        ),
    ]
